#!/usr/bin/env python3
"""
Generate all figures from the NHSB paper.

This script reproduces Figures 2–5 from:
    Reimer Morales (2026), "Near-Horizon Scrambling Brane."

Usage:
    python generate_paper_figures.py

Outputs:
    fig2_waveform_diagnostic.pdf
    fig3_channels.pdf
    fig4_pe_recovery.pdf
    fig5_source_variation.pdf

Note: Figure 1 (schematic) is a conceptual diagram and is not
generated by this script.
"""

import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from nhsb_waveform import NHSBWaveform, NHSBParams, SourceParams
from nhsb_waveform.tapers import taper_conservative, taper_heating, taper_ringdown
from nhsb_waveform.constitutive import effective_tidal_deformability, cavity_timescale
from nhsb_waveform.fisher import fisher_matrix
from nhsb_waveform.mcmc import run_mcmc
from nhsb_waveform.params import MTSUN_SI

PI = np.pi


def main():
    f = np.arange(20.0, 512.0, 0.5)
    src = SourceParams(m1=35, m2=30, D_L=410)
    wf = NHSBWaveform()

    print("Generating Figure 2: Waveform diagnostic...")
    make_fig2(f, src, wf)

    print("Generating Figure 3: Channel hierarchy...")
    make_fig3(f, src)

    print("Generating Figure 4: MCMC recovery...")
    make_fig4(f, src)

    print("Generating Figure 5: Source variation...")
    make_fig5(src)

    print("\nAll figures saved.")


def make_fig2(f, src, wf):
    """Four-panel waveform diagnostic (Fig. 2)."""
    configs = [
        ("Conservative", NHSBParams(1e-8, 0.2, 0.95, 1.0), 'C0'),
        ("Moderate", NHSBParams(1e-5, 1.0, 0.90, 0.7), 'C1'),
        ("Strong", NHSBParams(1e-4, 3.0, 0.80, 0.5), 'C3'),
    ]
    h_bbh = wf.h_tilde_bbh(f, src)

    fig, axes = plt.subplots(2, 2, figsize=(12, 8))
    for label, nhsb, color in configs:
        h = wf.h_tilde(f, src, nhsb)
        dpsi = wf.phase_deformation(f, src, nhsb)
        tau_c = cavity_timescale(src.M_final_seconds, nhsb.epsilon)
        Leff = effective_tidal_deformability(f, nhsb, tau_c)

        axes[0, 0].loglog(f, np.abs(h) * f, color=color, label=label, alpha=0.8)
        axes[0, 1].plot(f, dpsi, color=color, label=label, alpha=0.8)
        axes[1, 1].plot(f, Leff, color=color, label=label, alpha=0.8)

    axes[0, 0].loglog(f, np.abs(h_bbh) * f, 'k--', lw=1, label='BBH')
    axes[0, 0].set_ylabel(r'$|h(f)| \times f$')
    axes[0, 0].legend(fontsize=7)
    axes[0, 0].set_title('(a) Amplitude spectrum')

    axes[0, 1].set_ylabel(r'$\Delta\Psi$ [rad]')
    axes[0, 1].legend(fontsize=7)
    axes[0, 1].set_title('(b) Phase deviation')

    axes[1, 0].plot(f, taper_conservative(f, src.f_peak), label=r'$W_\Lambda$')
    axes[1, 0].plot(f, taper_heating(f, src.f_peak), label=r'$W_A$')
    axes[1, 0].plot(f, taper_ringdown(f, src.f_220), label=r'$W_R$')
    axes[1, 0].axvline(src.f_peak, color='gray', ls=':', lw=0.5)
    axes[1, 0].axvline(src.f_220, color='gray', ls='--', lw=0.5)
    axes[1, 0].legend(fontsize=7)
    axes[1, 0].set_title('(c) Taper windows')

    axes[1, 1].set_ylabel(r'$\Lambda_{\rm eff}(f)$')
    axes[1, 1].legend(fontsize=7)
    axes[1, 1].set_title(r'(d) Effective tidal deformability')

    for ax in axes.flat:
        ax.set_xlabel('f [Hz]')
    plt.tight_layout()
    plt.savefig('fig2_waveform_diagnostic.pdf', bbox_inches='tight', dpi=150)
    plt.close()


def make_fig3(f, src):
    """Channel hierarchy bar chart (Fig. 3)."""
    _, sigma, _ = fisher_matrix(f, src, snr_target=24)
    fig, ax = plt.subplots(figsize=(6, 4))
    bars = ax.bar(['Conservative\ntidal', 'Dissipative\nheating'],
                  [sigma[0], sigma[1]], color=['#2E8B8B', '#C06030'],
                  width=0.5)
    ax.set_ylabel(r'$1\sigma$ measurement precision')
    ax.set_title('Channel Hierarchy (aLIGO design, GW150914-like)')
    ax.annotate(f'~{sigma[0]/sigma[1]:.0f}×', xy=(0.5, sigma[1]*2),
                fontsize=14, ha='center', color='#C06030')
    for bar, val in zip(bars, [sigma[0], sigma[1]]):
        ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 10,
                f'~{val:.0f}', ha='center', fontsize=9)
    plt.tight_layout()
    plt.savefig('fig3_channels.pdf', bbox_inches='tight', dpi=150)
    plt.close()


def make_fig4(f, src):
    """MCMC injection recovery, 4 panels (Fig. 4)."""
    cases = [
        ("BBH null", NHSBParams(1e-8, 0.0, 1.0, 1.0)),
        ("Strong", NHSBParams(1e-8, 5.0, 0.5, 1.0)),
        ("Moderate", NHSBParams(1e-8, 3.0, 0.8, 1.0)),
        ("Conservative", NHSBParams(1e-8, 0.2, 0.95, 1.0)),
    ]
    fig, axes = plt.subplots(1, 4, figsize=(16, 4))
    for ax, (label, nhsb) in zip(axes, cases):
        chain, _ = run_mcmc(f, src, nhsb, snr_target=1000)
        ax.hist2d(chain[::3, 0], chain[::3, 1], bins=40,
                  cmap='Blues', density=True, rasterized=True)
        ax.plot(nhsb.Lambda_star, nhsb.A_abs, 'r+', ms=14, mew=2.5)
        ax.set_xlabel(r'$\Lambda_\star$')
        if ax == axes[0]:
            ax.set_ylabel(r'$\mathcal{A}$')
        ax.set_title(f"{label}\n(Λ★={nhsb.Lambda_star}, A={nhsb.A_abs})",
                     fontsize=8)
        ax.set_xlim(-8, 8); ax.set_ylim(0, 1)
    fig.suptitle('NHSB Parameter Recovery: Toy-Baseline MCMC at SNR = 1000',
                 fontsize=11, y=1.02)
    plt.tight_layout()
    plt.savefig('fig4_pe_recovery.pdf', bbox_inches='tight', dpi=150)
    plt.close()


def make_fig5(src_ref):
    """Source-parameter variation, 4 panels (Fig. 5)."""
    sources = [
        (r"$35+30\,M_\odot$", SourceParams(35, 30)),
        (r"$20+15\,M_\odot$", SourceParams(20, 15)),
        (r"$50+40\,M_\odot$", SourceParams(50, 40)),
        (r"$40+15\,M_\odot$ ($q\!=\!2.7$)", SourceParams(40, 15)),
    ]
    nhsb = NHSBParams(1e-8, 3.0, 0.8, 1.0)
    fig, axes = plt.subplots(1, 4, figsize=(16, 4))
    for ax, (label, src) in zip(axes, sources):
        f = np.arange(20.0, 512.0, 0.5)
        chain, _ = run_mcmc(f, src, nhsb, snr_target=1000)
        ax.hist2d(chain[::3, 0], chain[::3, 1], bins=40,
                  cmap='Blues', density=True, rasterized=True)
        ax.plot(nhsb.Lambda_star, nhsb.A_abs, 'r+', ms=14, mew=2.5)
        ax.set_xlabel(r'$\Lambda_\star$')
        if ax == axes[0]:
            ax.set_ylabel(r'$\mathcal{A}$')
        ax.set_title(label, fontsize=9)
        ax.set_xlim(-8, 8); ax.set_ylim(0, 1)
    fig.suptitle('Source-Parameter Variation: Moderate NHSB Injection at SNR = 1000',
                 fontsize=11, y=1.02)
    plt.tight_layout()
    plt.savefig('fig5_source_variation.pdf', bbox_inches='tight', dpi=150)
    plt.close()


if __name__ == "__main__":
    main()
